### ISSUE TITLE
"slug" is mentioned in Document.ts but does not appear in the api search response.

### ISSUE THREAD

**Issue by danielhuggins** [prismicio/prismic-javascript#37] opened 2018-03-20 20:41 UTC
There is a "slugs" property, but no singular "slug" property.

**Comment by danielhuggins** [comment] 2018-03-20 20:44
Uh, also in Document.ts alternateLanguages, firstPublicationDate and lastPublicationDate are given as camelCase but in the search response they are snake_case. Bug?

**Comment by levimykel** [comment] 2018-03-22 16:04
Hi @danielhuggins, thanks for reporting this. Someone will look into this as soon as we are able.

**Comment by danielhuggins** [comment] 2018-04-07 10:16
Yeah there's also the problem that "Document" is being confused for the
browser "Document" type.

**Comment by despairblue** [comment] 2018-05-22 12:15
@danielhuggins @levimykel #45 fixes this. Would be awesome if someone could merge that.

**Comment by despairblue** [comment] 2018-05-22 12:19
Oh #38 is also fixing this and the approach in #39 is also really nice and similar to how the mongodb driver is typed.

**Comment by srenault** [comment] 2018-06-07 08:51
Fixed in https://github.com/prismicio/prismic-javascript/pull/48

**Closed by srenault** 2018-06-07 08:51 UTC

**Comment by despairblue** [comment] 2018-06-07 11:07
@srenault Sorry but that does not fix that the document exported is still the one coming from dom.d.ts because the imports are missing that the other PRs add.

Should I open another issue for that?

**Comment by srenault** [comment] 2018-06-07 13:14
Hey @despairblue. How can I reproduce your issue?
